version: 2

models:
  - name: stg_pcns
    description: "Staging model for Primary Care Network data"
    columns:
      - name: pcn_id
        description: "Primary key for PCN"
        tests:
          - unique
          - not_null
      - name: pcn_name
        description: "Name of the PCN"
        tests:
          - not_null

  - name: stg_practices
    description: "Staging model for practice data"
    columns:
      - name: practice_id
        description: "Primary key for practice"
        tests:
          - unique
          - not_null
      - name: practice_name
        description: "Name of the practice"
        tests:
          - not_null
      - name: location
        description: "Location of the practice"
      - name: established_date
        description: "Date when practice was established"
      - name: pcn
        description: "Foreign key to PCN"
        tests:
          - relationships:
              to: ref('stg_pcns')
              field: pcn_id
              severity: warn  # Warn about invalid PCN references

  - name: stg_patients
    description: "Staging model for patient data"
    columns:
      - name: patient_id
        description: "Primary key for patient"
        tests:
          - unique:
              severity: warn  # Warn about duplicates, don't fail
          - not_null:
              severity: warn  # Warn about nulls, don't fail
      - name: practice_id
        description: "Foreign key to practice"
        tests:
          - relationships:
              to: ref('stg_practices')
              field: practice_id
              severity: warn  # Warn about invalid practice references
      - name: age
        description: "Patient age"
      - name: gender
        description: "Patient gender"
      - name: registration_date
        description: "Date when patient registered"
      - name: conditions
        description: "JSON array of patient conditions"
      - name: contact
        description: "JSON object containing contact information"

  - name: stg_activities
    description: "Staging model for activity data"
    columns:
      - name: activity_id
        description: "Primary key for activity"
        tests:
          - unique
          - not_null
      - name: patient_id
        description: "Foreign key to patient"
        tests:
          - relationships:
              to: ref('stg_patients')
              field: patient_id
              severity: warn  # Warn about orphaned activities
      - name: activity_type
        description: "Type of activity (consultation, prescription, lab_test, etc.)"
      - name: activity_date
        description: "Date and time of the activity"
      - name: duration_minutes
        description: "Duration of activity in minutes" 